backend:
  name: git-gateway
  repo: EmanuelKrabNL/emanuelkrabnl.github.io
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "posts"
    label: "Blogposts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publicatiedatum", name: "date", widget: "datetime" }
      - { label: "Categorieën", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
